# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "http://zhulj.net/"

# Title of your site
title = "Liang-Jun Zhu"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2018 Liang-Jun Zhu"

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "crazyzlj"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-75301149-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "default"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "classic"

  # Your details.
  name = "Liang-Jun Zhu"
  role = "PhD Student of GIS"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ {name="State Key Laboratory of Resources and Environmental Information System (LERIS)", url="http://www.lreis.ac.cn/"},
                    { name = "Institute of Geographic Sciences and Natural Resources Research (IGSNRR), Chinese Academy of Sciences (CAS)", url = "http://www.igsnrr.cas.cn/" } ]

  gravatar = true  # Get your avatar from Gravatar.com? (true/false)
  avatar = "zlj@lreis.ac.cn"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "zlj@lreis.ac.cn"
  address = "Room 2415, 11A Datun Road, Chaoyang District, Beijing 100101, PR China"
  address_cn = "北京市朝阳区安定门外大屯路甲11号2415, 邮编100101"
  office_hours = "Friday 14:00 to 17:00 or email for appointment"
  office_hours_cn = "周五 14:00 至 17:00 或邮件预约"
  #phone = "+86 13146157316"
  skype = "live:crazyzlj"
  #telegram = ""

  # Enable Keybase in Contact widget by entering your keybase.io username.
  keybase = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15

  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "15:04"

  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages and styles, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["cpp", "python", "javascript", "markdown", "matlab", "r"]
  highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Chinese publication',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "2006-01-02"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 0

  # Social/Academic Networking
  #
  # Icon pack "fab" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fas" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fontawesome.com/icons
  #
  # Icon pack "ai" includes the following academic icons:
  #
  #   cv, google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:zlj@lreis.ac.cn"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/LiangjunZhu"

  [[params.social]]
    icon = "weibo"
    icon_pack = "fa"
    link = "//weibo.com/crazyzlj"

  [[params.social]]
    icon = "tasks"
    icon_pack = "fa"
    link = "/tweet/"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=FkNIpcQAAAAJ&hl"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Liangjun_Zhu"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/crazyzlj"

  # Link to a PDF of your resume/CV from the About widget.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  [[params.social]]
    icon = "cv"
     icon_pack = "ai"
     link = "files/cv_ljzhu_en.pdf"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Course"
  url = "#course"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[menu.main]]
    name = "CV"
    url = "files/cv_ljzhu_en.pdf"
    weight = 7

# Search.
[params.search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the website.
[languages.en]

[languages.zh]
  languageCode = "zh-Hans"
  title = "朱良君"
  [languages.zh.params]
    name = "朱良君"
    role = "GIS博士研究生"

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Chinese publication',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  [[languages.zh.menu.main]]
    name = "首页"
    url = "/zh/#about"
    weight = 1

  [[languages.zh.menu.main]]
    name = "论著"
    url = "/zh/#publications_selected"
    weight = 2

  [[languages.zh.menu.main]]
    name = "博客"
    url = "/zh/#posts"
    weight = 3

  [[languages.zh.menu.main]]
    name = "项目"
    url = "/zh/#projects"
    weight = 4

  [[languages.zh.menu.main]]
    name = "教程"
    url = "/zh/#course"
    weight = 5

  [[languages.zh.menu.main]]
    name = "联系"
    url = "/zh/#contact"
    weight = 6

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  [[languages.zh.menu.main]]
      name = "简历"
      url = "files/cv_ljzhu_chs.pdf"
      weight = 7

